### ISSUE TITLE
Brief description of your problem

### ISSUE THREAD

**Issue by wvthoog** [PixelExperience/android-issues#987]
## Build date

```
Own build on a Proxmox Ubuntu 20.04 VM with Nvidia vGPU enabled
```

`
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Nov_30_19:08:53_PST_2020
Cuda compilation tools, release 11.2, V11.2.67
Build cuda_11.2.r11.2/compiler.29373293_0
`

## Expected Behavior

```
Build without errors
```

## Current Behavior

```
When building a ROM for Redmi Note 10 Pro i'm getting some errors while the build attempts to use CUDA. My build machine is a Ubuntu 20.04 VM hosted on Proxmox with a Nvidia Virtual GPU (vGPU). (Tesla P40)
```

`
In file included from ../../../../../../kernel/xiaomi/sm6150/init/version.c:9:
./include/generated/compile.h:7:24: warning: missing terminating '"' character [-Winvalid-pp-token]
#define LINUX_COMPILER "Android (6877366 based on r383902b1) clang version 11.0.2 (https://android.googlesource.com/toolchai
n/llvm-project b397f81060ce6d701042b782172ed13bee898b79)
                       ^
./include/generated/compile.h:8:1: error: unknown type name 'Found'
Found CUDA installation: /usr/local/cuda, version 7.0, GNU ld (binutils-2.27-bd24d23f) 2.27.0.20170315"
^
./include/generated/compile.h:8:11: error: expected ';' after top level declarator
Found CUDA installation: /usr/local/cuda, version 7.0, GNU ld (binutils-2.27-bd24d23f) 2.27.0.20170315"
          ^
          ;
./include/generated/compile.h:8:103: warning: missing terminating '"' character [-Winvalid-pp-token]
Found CUDA installation: /usr/local/cuda, version 7.0, GNU ld (binutils-2.27-bd24d23f) 2.27.0.20170315"
                                                                                                      ^
In file included from ../../../../../../kernel/xiaomi/sm6150/init/version.c:10:
In file included from ../../../../../../kernel/xiaomi/sm6150/include/linux/module.h:9:
In file included from ../../../../../../kernel/xiaomi/sm6150/include/linux/list.h:5:
../../../../../../kernel/xiaomi/sm6150/include/linux/types.h:102:10: error: unknown type name '__s8'; did you mean '__u8'?
typedef         __s8            int8_t;
                ^~~~
                __u8
../../../../../../kernel/xiaomi/sm6150/include/uapi/asm-generic/int-ll64.h:21:23: note: '__u8' declared here
typedef unsigned char __u8;
                      ^
../../../../../../kernel/xiaomi/sm6150/init/version.c:46:26: error: expected ';' after top level declarator
        LINUX_COMPILE_HOST ") (" LINUX_COMPILER ") " UTS_VERSION "\n";
                                ^
                                ;
../../../../../../kernel/xiaomi/sm6150/init/version.c:51:6: error: expected ';' after top level declarator
        " (" LINUX_COMPILER ") %s\n";
            ^
            ;
2 warnings and 5 errors generated.
make[2]: *** [/home/wvthoog/android/pixel-experience/kernel/xiaomi/sm6150/scripts/Makefile.build:361: init/version.o] Error 
1
make[2]: *** Waiting for unfinished jobs....
`

## Possible Solution

```
Somewhere there are some syntax errors in the source files when using CUDA in the build process
```

Tried building it on another VM (Ubuntu 20.04) on the same Proxmox server but this time without a Nvidia GPU which build the ROM successfully.

## Steps to Reproduce

```
1. Download latest source files and checkout device Sweet
2. Start build process
3. After kernel build these errors occur
```

/device sweet
/version eleven_plus

**Comment by pixelexperiencebot** [comment]
Validation failed, this issue will be closed for not complying with the established standards.

Errors:
- Invalid issue template

**Comment by Jorg3Lucas** [comment]
Hello @wvthoog 
Fix: Study a little more to resolve the compilation error

**Comment by wvthoog** [comment]
@Jorg3Lucas 

the thing i can find is that CUDA is the wrong version (7.0 instead of 11.2) When i use a different Clang version (12 instead of 11) it shows the correct CUDA version but still fails to build. 

I'm clearly missing something obvious. Any pointers on how to resolve this is greatly appreciated.
